# Generated by Django 3.2.25 on 2025-10-21 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('AdminId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('AdminPass', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'TB_Admin',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('message', models.CharField(max_length=60)),
                ('user_status', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('visitor', 'Visitor')], default='visitor', max_length=10)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Review',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('CustId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=255)),
                ('userEmail', models.EmailField(max_length=254, unique=True)),
                ('userPass', models.CharField(max_length=255)),
                ('userImage', models.ImageField(default='profile_images/default.png', upload_to='profile_images/')),
            ],
            options={
                'db_table': 'TB_Users',
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Chat', max_length=255)),
                ('messages', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
