# Generated by Django 3.2.25 on 2025-11-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='created_at',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
