# Generated by Django 3.2.25 on 2025-11-21 07:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20251120_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userImage',
            field=cloudinary.models.CloudinaryField(default='default_h6ywr4.png', max_length=255, verbose_name='Profile Images'),
        ),
        migrations.DeleteModel(
            name='ChatHistory',
        ),
    ]
